//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.18052
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace daan.ui.main.ServiceToAPP {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://Routespecimen.commser.sea.red", ConfigurationName="ServiceToAPP.RouteSpecimenServicePortType")]
    public interface RouteSpecimenServicePortType {
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="out")]
        string routeSpecimen(string in0, string in1, string in2, string in3, string in4);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface RouteSpecimenServicePortTypeChannel : daan.ui.main.ServiceToAPP.RouteSpecimenServicePortType, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class RouteSpecimenServicePortTypeClient : System.ServiceModel.ClientBase<daan.ui.main.ServiceToAPP.RouteSpecimenServicePortType>, daan.ui.main.ServiceToAPP.RouteSpecimenServicePortType {
        
        public RouteSpecimenServicePortTypeClient() {
        }
        
        public RouteSpecimenServicePortTypeClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public RouteSpecimenServicePortTypeClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public RouteSpecimenServicePortTypeClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public RouteSpecimenServicePortTypeClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string routeSpecimen(string in0, string in1, string in2, string in3, string in4) {
            return base.Channel.routeSpecimen(in0, in1, in2, in3, in4);
        }
    }
}
