/*
insert license info here
*/
using System;

namespace daan.domain
{
    /// <summary>
    ///	Generated by MyGeneration using the IBatis Object Mapping template
    /// </summary>
    [Serializable]
    public sealed class Dictproductdetail : BaseDomain
    {
        #region Private Members
        private bool isChanged;
        private bool isDeleted;
        private double? productid;
        private double? testgroupid;
        private DateTime? createdate;
        private double? finalprice;
        private string issendouttest;
        private double? sendoutcustomerid;

        /*登记 使用 zhouy*/
        /// <summary>
        /// 分管原则 
        /// </summary>
        public string Tubegroup { get; set; }

        /// <summary>
        /// 条码 
        /// </summary>
        public string Barcode { get; set; }

        #endregion

        #region Default ( Empty ) Class Constuctor
        ///// <summary>
        ///// default constructor
        ///// </summary>
        //public Dictproductdetail()
        //{
        //    productid = null;
        //    testgroupid = null;
        //    createdate = new DateTime();
        //    finalprice = null;
        //    issendouttest = null;
        //    sendoutcustomerid = null;
        //}
        #endregion // End of Default ( Empty ) Class Constuctor

        #region Public Properties

        /// <summary>
        /// 套餐ID 对应dicttest表testtype=2的dicttestid
        /// </summary>	
        [LogInfo("套餐ID 对应dicttest表testtype=2的dicttestid")]
        public double? Productid
        {
            get { return productid; }
            set { isChanged |= (productid != value); productid = value; }
        }

        /// <summary>
        /// 组合ID 对应dicttest表testtype=1的dicttestid
        /// </summary>	
        [LogInfo("组合ID 对应dicttest表testtype=1的dicttestid")]
        public double? Testgroupid
        {
            get { return testgroupid; }
            set { isChanged |= (testgroupid != value); testgroupid = value; }
        }

        /// <summary>
        /// 
        /// </summary>	
        [LogInfo("")]
        public DateTime? Createdate
        {
            get { return createdate; }
            set { isChanged |= (createdate != value); createdate = value; }
        }

        /// <summary>
        /// 最终价钱
        /// </summary>	
        [LogInfo("最终价钱")]
        public double? Finalprice
        {
            get { return finalprice; }
            set { isChanged |= (finalprice != value); finalprice = value; }
        }

        /// <summary>
        /// 是否外包项目0-否  1-是
        /// </summary>	
        [LogInfo("是否外包项目0-否  1-是")]
        public string Issendouttest
        {
            get { return issendouttest; }
            set { isChanged |= (issendouttest != value); issendouttest = value; }
        }

        /// <summary>
        /// 外包客户ID
        /// </summary>	
        [LogInfo("外包客户ID")]
        public double? Sendoutcustomerid
        {
            get { return sendoutcustomerid; }
            set { isChanged |= (sendoutcustomerid != value); sendoutcustomerid = value; }
        }

        /// <summary>
        /// Returns whether or not the object has changed it's values.
        /// </summary>
        public bool IsChanged
        {
            get { return isChanged; }
        }

        /// <summary>
        /// Returns whether or not the object has changed it's values.
        /// </summary>
        public bool IsDeleted
        {
            get { return isDeleted; }
        }

        #endregion


        #region Public Functions

        /// <summary>
        /// mark the item as deleted
        /// </summary>
        public void MarkAsDeleted()
        {
            isDeleted = true;
            isChanged = true;
        }

        #endregion


    }
}
