/*
insert license info here
*/
using System;

namespace daan.domain
{
	/// <summary>
	///	Generated by MyGeneration using the IBatis Object Mapping template
	/// </summary>
	[Serializable]
	public sealed class Dictmedhistory:BaseDomain
	{
		#region Private Members
		private bool isChanged;
		private bool isDeleted;
		private double? dictmedhistoryid; 
		private double? dictmemberid; 
		private string diseasename; 
		private DateTime? diseasedate; 
		private string istreat; 
		private string istakemedicine; 
		private string medname; 
		private DateTime? createdate; 		
		#endregion
		
		#region Default ( Empty ) Class Constuctor
		/// <summary>
		/// default constructor
		/// </summary>
		public Dictmedhistory()
		{
			dictmedhistoryid = null; 
			dictmemberid = null; 
			diseasename = null; 
			diseasedate = new DateTime(); 
			istreat = null; 
			istakemedicine = null; 
			medname = null; 
			createdate = new DateTime(); 
		}
		#endregion // End of Default ( Empty ) Class Constuctor
		
		#region Public Properties
			
		/// <summary>
		/// 即往病史主键
		/// </summary>	
		[LogInfo("即往病史主键")]
		public double? Dictmedhistoryid
		{
			get { return dictmedhistoryid; }
			set { isChanged |= (dictmedhistoryid != value); dictmedhistoryid = value; }
		}
			
		/// <summary>
		/// 
		/// </summary>	
		[LogInfo("")]
		public double? Dictmemberid
		{
			get { return dictmemberid; }
			set { isChanged |= (dictmemberid != value); dictmemberid = value; }
		}
			
		/// <summary>
		/// 疾病名称
		/// </summary>	
		[LogInfo("疾病名称")]
		public string Diseasename
		{
			get { return diseasename; }
			set	
			{
				if( value!= null && value.Length > 200)
					throw new ArgumentOutOfRangeException("Invalid value for Diseasename", value, value.ToString());
				
				isChanged |= (diseasename != value); diseasename = value;
			}
		}
			
		/// <summary>
		/// 患病时间(年)
		/// </summary>	
		[LogInfo("患病时间(年)")]
		public DateTime? Diseasedate
		{
			get { return diseasedate; }
			set { isChanged |= (diseasedate != value); diseasedate = value; }
		}
			
		/// <summary>
		/// 是否治疗
		/// </summary>	
		[LogInfo("是否治疗")]
		public string Istreat
		{
			get { return istreat; }
			set	
			{
				if( value!= null && value.Length > 1)
					throw new ArgumentOutOfRangeException("Invalid value for Istreat", value, value.ToString());
				
				isChanged |= (istreat != value); istreat = value;
			}
		}
			
		/// <summary>
		/// 是否服药
		/// </summary>	
		[LogInfo("是否服药")]
		public string Istakemedicine
		{
			get { return istakemedicine; }
			set	
			{
				if( value!= null && value.Length > 1)
					throw new ArgumentOutOfRangeException("Invalid value for Istakemedicine", value, value.ToString());
				
				isChanged |= (istakemedicine != value); istakemedicine = value;
			}
		}
			
		/// <summary>
		/// 药品名称
		/// </summary>	
		[LogInfo("药品名称")]
		public string Medname
		{
			get { return medname; }
			set	
			{
				if( value!= null && value.Length > 200)
					throw new ArgumentOutOfRangeException("Invalid value for Medname", value, value.ToString());
				
				isChanged |= (medname != value); medname = value;
			}
		}
			
		/// <summary>
		/// 创建时间
		/// </summary>	
		[LogInfo("创建时间")]
		public DateTime? Createdate
		{
			get { return createdate; }
			set { isChanged |= (createdate != value); createdate = value; }
		}
			
		/// <summary>
		/// Returns whether or not the object has changed it's values.
		/// </summary>
		public bool IsChanged
		{
			get { return isChanged; }
		}
		
		/// <summary>
		/// Returns whether or not the object has changed it's values.
		/// </summary>
		public bool IsDeleted
		{
			get { return isDeleted; }
		}
		
		#endregion 
		
		
		#region Public Functions
		
		/// <summary>
		/// mark the item as deleted
		/// </summary>
		public void MarkAsDeleted()
		{
			isDeleted = true;
			isChanged = true;
		}
		
		#endregion
		
		
	}
}
