/*
insert license info here
*/
using System;

namespace daan.domain
{
	/// <summary>
	///	Generated by MyGeneration using the IBatis Object Mapping template
	/// </summary>
	[Serializable]
	public sealed class Dictcustomerdiscounted:BaseDomain
	{
		#region Private Members
		private bool isChanged;
		private bool isDeleted;
		private double? dictcustomerdiscountid; 
		private double? dictcustomerid; 
		private double? discounted; 
		private DateTime begindate; 
		private DateTime enddate; 
		private double? updateby; 
		private DateTime updatedate; 
		private double? sendoutprice; 
		private DateTime createdate;
        private string _customername;

        private double? productid;
        private double? price;
        private string active;
        private double? auditby;
        private DateTime auditdate;
        private double? dictsubcompanyid;
		#endregion
		
		#region Default ( Empty ) Class Constuctor
		/// <summary>
		/// default constructor
		/// </summary>
		public Dictcustomerdiscounted()
		{
			dictcustomerdiscountid = 0; 
			dictcustomerid = 0; 
			discounted = null; 
			begindate = new DateTime(); 
			enddate = new DateTime(); 
			updateby = null; 
			updatedate = new DateTime(); 
			sendoutprice = null; 
			createdate = new DateTime();
            _customername = null;
            productid = null;
            price = null;
            active ="0";
            auditby = null;
            auditdate = new DateTime();
            dictsubcompanyid = null;
		}
		#endregion // End of Default ( Empty ) Class Constuctor
		
		#region Public Properties
			
		/// <summary>
		/// 主键，自动ID
		/// </summary>	
		[LogInfo("主键，自动ID")]
		public double? Dictcustomerdiscountid
		{
			get { return dictcustomerdiscountid; }
			set { isChanged |= (dictcustomerdiscountid != value); dictcustomerdiscountid = value; }
		}
			
		/// <summary>
		/// 客户ID
		/// </summary>	
		[LogInfo("客户ID")]
		public double? Dictcustomerid
		{
			get { return dictcustomerid; }
			set { isChanged |= (dictcustomerid != value); dictcustomerid = value; }
		}

        /// <summary>
        /// 客户名称
        /// </summary>		
        public string Customername
        {
            get { return _customername; }
            set
            {
                if (value != null && value.Length > 100)
                    throw new ArgumentOutOfRangeException("Invalid value for Customername", value, value.ToString());

                isChanged |= (_customername != value); _customername = value;
            }
        }
		/// <summary>
		/// 折扣率
		/// </summary>	
		[LogInfo("折扣率")]
		public double? Discounted
		{
			get { return discounted; }
			set { isChanged |= (discounted != value); discounted = value; }
		}
			
		/// <summary>
		/// 开始日期
		/// </summary>	
		[LogInfo("开始日期")]
		public DateTime Begindate
		{
            get { return begindate; }
			set { isChanged |= (begindate != value); begindate = value; }
		}
			
		/// <summary>
		/// 结束日期
		/// </summary>	
		[LogInfo("结束日期")]
		public DateTime Enddate
		{
			get { return enddate; }
			set { isChanged |= (enddate != value); enddate = value; }
		}
			
		/// <summary>
		/// 维护人
		/// </summary>	
		[LogInfo("维护人")]
		public double? Updateby
		{
			get { return updateby; }
			set { isChanged |= (updateby != value); updateby = value; }
		}
			
		/// <summary>
		/// 维护日期
		/// </summary>	
		[LogInfo("维护日期")]
		public DateTime Updatedate
		{
			get { return updatedate; }
			set { isChanged |= (updatedate != value); updatedate = value; }
		}
			
		/// <summary>
		/// --
		/// </summary>	
		[LogInfo("--")]
		public double? Sendoutprice
		{
			get { return sendoutprice; }
			set { isChanged |= (sendoutprice != value); sendoutprice = value; }
		}
			
		/// <summary>
		/// 创建时间
		/// </summary>	
		[LogInfo("创建时间")]
		public DateTime Createdate
		{
			get { return createdate; }
			set { isChanged |= (createdate != value); createdate = value; }
		}

        /// <summary>
        /// 套餐ID
        /// </summary>
        [LogInfo("套餐ID")]
        public double? Productid
        {
            get { return productid; }
            set { isChanged |= (productid != value); productid = value; }
        }

        /// <summary>
        /// 套餐价格
        /// </summary>
        [LogInfo("套餐价格")]
        public double? Price
        {
            get { return price; }
            set { isChanged |= (price != value); price = value; }
        }

        /// <summary>
        /// 审核状态
        /// </summary>
        [LogInfo("审核状态")]
        public string Active
        {
            get { return active; }
            set { isChanged |= (active != value); active = value; }
        }
        /// <summary>
        /// 审核人ID
        /// </summary>
        [LogInfo("审核人ID")]
        public double? AuditBy
        {
            get { return auditby; }
            set { isChanged |= (auditby != value); auditby = value; }
        }

        /// <summary>
        /// 审核时间
        /// </summary>
        [LogInfo("审核时间")]
        public DateTime AuditDate
        {
            get { return auditdate; }
            set { isChanged |= (auditdate != value); auditdate = value; }
        }

        /// <summary>
        /// 签约子公司ID
        /// </summary>
        [LogInfo("签约子公司ID")]
        public double? DictSubCompanyID
        {
            get { return dictsubcompanyid; }
            set { isChanged |= (dictsubcompanyid != value); dictsubcompanyid = value; }
        }

		/// <summary>
		/// Returns whether or not the object has changed it's values.
		/// </summary>
		public bool IsChanged
		{
			get { return isChanged; }
		}
		
		/// <summary>
		/// Returns whether or not the object has changed it's values.
		/// </summary>
		public bool IsDeleted
		{
			get { return isDeleted; }
		}
		
		#endregion 
		
		
		#region Public Functions
		
		/// <summary>
		/// mark the item as deleted
		/// </summary>
		public void MarkAsDeleted()
		{
			isDeleted = true;
			isChanged = true;
		}
		
		#endregion
		
		
	}
}
