/*
insert license info here
*/
using System;

namespace daan.domain
{
	/// <summary>
	///	Generated by MyGeneration using the IBatis Object Mapping template
	/// </summary>
	[Serializable]
	public sealed class Dicttestgroupdetail:BaseDomain
	{
		#region Private Members
		private bool isChanged;
		private bool isDeleted;
		private double? testgroupid; 
		private DateTime? createdate; 
		private double? dicttestitemid; 		
		#endregion
		
		#region Default ( Empty ) Class Constuctor
		/// <summary>
		/// default constructor
		/// </summary>
        //public Dicttestgroupdetail()
        //{
        //    testgroupid = null; 
        //    createdate = new DateTime(); 
        //    dicttestitemid = null; 
        //}
		#endregion // End of Default ( Empty ) Class Constuctor
		
		#region Public Properties
			
		/// <summary>
		/// 组合ID
		/// </summary>	
		[LogInfo("组合ID")]
		public double? Testgroupid
		{
			get { return testgroupid; }
			set { isChanged |= (testgroupid != value); testgroupid = value; }
		}
			
		/// <summary>
		/// 
		/// </summary>	
		[LogInfo("")]
		public DateTime? Createdate
		{
			get { return createdate; }
			set { isChanged |= (createdate != value); createdate = value; }
		}
			
		/// <summary>
		/// 测试明细项ID
		/// </summary>	
		[LogInfo("测试明细项ID")]
		public double? Dicttestitemid
		{
			get { return dicttestitemid; }
			set { isChanged |= (dicttestitemid != value); dicttestitemid = value; }
		}
			
		/// <summary>
		/// Returns whether or not the object has changed it's values.
		/// </summary>
		public bool IsChanged
		{
			get { return isChanged; }
		}
		
		/// <summary>
		/// Returns whether or not the object has changed it's values.
		/// </summary>
		public bool IsDeleted
		{
			get { return isDeleted; }
		}
		
		#endregion 
		
		
		#region Public Functions
		
		/// <summary>
		/// mark the item as deleted
		/// </summary>
		public void MarkAsDeleted()
		{
			isDeleted = true;
			isChanged = true;
		}
		
		#endregion
		
		
	}
}
