/*
insert license info here
*/
using System;

namespace daan.domain
{
    /// <summary>
    ///	Generated by MyGeneration using the IBatis Object Mapping template
    /// </summary>
    [Serializable]
    public sealed class OrderRegister : BaseDomain
    {
        #region Private Members
        /// <summary>
        /// 全国统一码
        /// </summary>
        public string Uniqueid { get; set; }

        /// <summary>
        /// 套餐ID
        /// </summary>
        public double? Productid { get; set; }
        /// <summary>
        /// 套餐名
        /// </summary>
        public string Productname { get; set; }
        /// <summary>
        /// 组合|项目ID
        /// </summary>
        public double? Id { get; set; }
        /// <summary>
        /// 组合|项目编码
        /// </summary>
        public string Code { get; set; }
        /// <summary>
        /// 组合|项目名
        /// </summary>
        public string Name { get; set; }
        /// <summary>
        /// 组合OR项目 
        /// </summary>
        public string Type { get; set; }

        /// <summary>
        /// 是否组合
        /// </summary>
        public bool IsGroup
        {
            get
            {
                if (Type == "1") { return true; }
                else { return false; }
            }
        }
        /// <summary>
        /// 是否套餐 true 套餐   false 非套餐
        /// </summary>
        public bool IsProduct
        {
            get
            {
                if (Productid != null) { return true; }
                else { return false; }
            }
        }
        /// <summary>
        /// 是否追加
        /// </summary>
        public string Isadd { get; set; }
        /// <summary>
        /// 追加人ID
        /// </summary>
        public double? Adduserid { get; set; }
        /// <summary>
        /// 追加人名称
        /// </summary>
        public string Addusername { get; set; }
        /// <summary>
        /// 继续测试状态 0 停止测试 1 正常
        /// </summary>
        public string Isactive { get; set; }
        /// <summary>
        /// 账单清单生成状态
        /// </summary>
        public string Billed { get; set; }
        /// <summary>
        /// 外包账单生成状态
        /// </summary>
        public string Sendbilled { get; set; }
        /// <summary>
        /// 外包单位
        /// </summary>
        public double? Sendoutcustomerid { get; set; }
        /// <summary>
        /// 外包单位名称 
        /// </summary>
        public string Sencustomername { get; set; }
        /// <summary>
        /// 是否可删除  true 可删除，false 不可删除
        /// </summary>
        public bool Isdelete
        {
            get
            {
                bool b = true;
                //账单或者外包账单有生成则不可删除
                if (Billed == "1" || Sendbilled == "1")
                {
                    b = false;
                }
                return b;
            }
            set { Isdelete = value; }
        }

        /// <summary>
        /// 分管原则 
        /// </summary>
        public string Tubegroup { get; set; }

        /// <summary>
        /// 条码 
        /// </summary>
        public string Barcode { get; set; }

        /// <summary>
        /// 状态
        /// </summary>
        public string Status { get; set; }

        
        /// <summary>
        /// Orders状态
        /// </summary>
        public string Orderstatus { get; set; }
        

        #endregion

        public OrderRegister()
        {
            Uniqueid = null;
            Productid = null;
            Productname = "";
            Isadd = "0";
            Billed = "0";
            Sendbilled = "0";
            Tubegroup = null;
            Barcode = "";
            Status = "5";
        }

    }
}
