/*
insert license info here
*/
using System;

namespace daan.domain
{
	/// <summary>
	///	Generated by MyGeneration using the IBatis Object Mapping template
	/// </summary>
	[Serializable]
    public sealed class Orderdiagnosis : Dictlabdept
	{
		#region Private Members
		private bool isChanged;
		private bool isDeleted;
		private double? orderdiagnosisid; 
		private string ordernum; 
		private string diagnosisname; 
		private string diagnosistype; 
		private double? dictdiagnosisid; 
		private double? dictlabdeptid; 
		private string diseasedescription; 
		private string diseasecause; 
		private string suggestion; 
		private string engdiseasedescription; 
		private string engdiseasecause; 
		private string engsuggestion; 
		private DateTime createdate; 
		private string isdisease; 
		private double? displayorder;  		
		#endregion
		
		#region Default ( Empty ) Class Constuctor
		/// <summary>
		/// default constructor
		/// </summary>
		public Orderdiagnosis()
		{
			orderdiagnosisid = null; 
			ordernum = null; 
			diagnosisname = null; 
			diagnosistype = null; 
			dictdiagnosisid = null; 
			dictlabdeptid = null; 
			diseasedescription = null; 
			diseasecause = null; 
			suggestion = null; 
			engdiseasedescription = null; 
			engdiseasecause = null; 
			engsuggestion = null; 
			createdate = new DateTime(); 
			isdisease = null; 
			displayorder = null; 
		}
		#endregion // End of Default ( Empty ) Class Constuctor
		
		#region Public Properties
			
		/// <summary>
		/// 主键
		/// </summary>	
		[LogInfo("主键")]
		public double? Orderdiagnosisid
		{
			get { return orderdiagnosisid; }
			set { isChanged |= (orderdiagnosisid != value); orderdiagnosisid = value; }
		}
			
		/// <summary>
		/// 体检流水号
		/// </summary>	
		[LogInfo("体检流水号")]
		public string Ordernum
		{
			get { return ordernum; }
			set	
			{
				if( value!= null && value.Length > 50)
					throw new ArgumentOutOfRangeException("Invalid value for Ordernum", value, value.ToString());
				
				isChanged |= (ordernum != value); ordernum = value;
			}
		}
			
		/// <summary>
		/// 诊断名称
		/// </summary>	
		[LogInfo("诊断名称")]
		public string Diagnosisname
		{
			get { return diagnosisname; }
			set	
			{
				if( value!= null && value.Length > 200)
					throw new ArgumentOutOfRangeException("Invalid value for Diagnosisname", value, value.ToString());
				
				isChanged |= (diagnosisname != value); diagnosisname = value;
			}
		}
			
		/// <summary>
		/// 对应INITBASIC表BASICTYPE = DIAGNOSISTYPE
		/// </summary>	
		[LogInfo("对应INITBASIC表BASICTYPE = DIAGNOSISTYPE")]
		public string Diagnosistype
		{
			get { return diagnosistype; }
			set	
			{
				if( value!= null && value.Length > 50)
					throw new ArgumentOutOfRangeException("Invalid value for Diagnosistype", value, value.ToString());
				
				isChanged |= (diagnosistype != value); diagnosistype = value;
			}
		}
			
		/// <summary>
		/// 诊断ID
		/// </summary>	
		[LogInfo("诊断ID")]
		public double? Dictdiagnosisid
		{
			get { return dictdiagnosisid; }
			set { isChanged |= (dictdiagnosisid != value); dictdiagnosisid = value; }
		}
			
		/// <summary>
		/// 测试项物理实验室分组,对应表DICTLABDEPT
		/// </summary>	
		[LogInfo("测试项物理实验室分组,对应表DICTLABDEPT")]
		public double? Dictlabdeptid
		{
			get { return dictlabdeptid; }
			set { isChanged |= (dictlabdeptid != value); dictlabdeptid = value; }
		}
			
		/// <summary>
		/// 疾病描述
		/// </summary>	
		[LogInfo("疾病描述")]
		public string Diseasedescription
		{
			get { return diseasedescription; }
			set	
			{
				if( value!= null && value.Length > 4000)
					throw new ArgumentOutOfRangeException("Invalid value for Diseasedescription", value, value.ToString());
				
				isChanged |= (diseasedescription != value); diseasedescription = value;
			}
		}
			
		/// <summary>
		/// 病因
		/// </summary>	
		[LogInfo("病因")]
		public string Diseasecause
		{
			get { return diseasecause; }
			set	
			{
				if( value!= null && value.Length > 4000)
					throw new ArgumentOutOfRangeException("Invalid value for Diseasecause", value, value.ToString());
				
				isChanged |= (diseasecause != value); diseasecause = value;
			}
		}
			
		/// <summary>
		/// 建议内容
		/// </summary>	
		[LogInfo("建议内容")]
		public string Suggestion
		{
			get { return suggestion; }
			set	
			{
				if( value!= null && value.Length > 4000)
					throw new ArgumentOutOfRangeException("Invalid value for Suggestion", value, value.ToString());
				
				isChanged |= (suggestion != value); suggestion = value;
			}
		}
			
		/// <summary>
		/// 疾病描述（英文）
		/// </summary>	
		[LogInfo("疾病描述（英文）")]
		public string Engdiseasedescription
		{
			get { return engdiseasedescription; }
			set	
			{
				if( value!= null && value.Length > 4000)
					throw new ArgumentOutOfRangeException("Invalid value for Engdiseasedescription", value, value.ToString());
				
				isChanged |= (engdiseasedescription != value); engdiseasedescription = value;
			}
		}
			
		/// <summary>
		/// 病因（英文）
		/// </summary>	
		[LogInfo("病因（英文）")]
		public string Engdiseasecause
		{
			get { return engdiseasecause; }
			set	
			{
				if( value!= null && value.Length > 4000)
					throw new ArgumentOutOfRangeException("Invalid value for Engdiseasecause", value, value.ToString());
				
				isChanged |= (engdiseasecause != value); engdiseasecause = value;
			}
		}
			
		/// <summary>
		/// 建议内容（英文）
		/// </summary>	
		[LogInfo("建议内容（英文）")]
		public string Engsuggestion
		{
			get { return engsuggestion; }
			set	
			{
				if( value!= null && value.Length > 4000)
					throw new ArgumentOutOfRangeException("Invalid value for Engsuggestion", value, value.ToString());
				
				isChanged |= (engsuggestion != value); engsuggestion = value;
			}
		}
			
		/// <summary>
		/// 创建时间
		/// </summary>	
		[LogInfo("创建时间")]
		public DateTime Createdate
		{
			get { return createdate; }
			set { isChanged |= (createdate != value); createdate = value; }
		}
			
		/// <summary>
		/// 是否疾病  0 否  1 是
		/// </summary>	
		[LogInfo("是否疾病  0 否  1 是")]
		public string Isdisease
		{
			get { return isdisease; }
			set	
			{
				if( value!= null && value.Length > 1)
					throw new ArgumentOutOfRangeException("Invalid value for Isdisease", value, value.ToString());
				
				isChanged |= (isdisease != value); isdisease = value;
			}
		}
			
		/// <summary>
		/// 排序
		/// </summary>	
		[LogInfo("排序")]
		public double? Displayorder
		{
			get { return displayorder; }
			set { isChanged |= (displayorder != value); displayorder = value; }
		}			
			
		/// <summary>
		/// Returns whether or not the object has changed it's values.
		/// </summary>
		public bool IsChanged
		{
			get { return isChanged; }
		}
		
		/// <summary>
		/// Returns whether or not the object has changed it's values.
		/// </summary>
		public bool IsDeleted
		{
			get { return isDeleted; }
		}
		
		#endregion 
		
		
		#region Public Functions
		
		/// <summary>
		/// mark the item as deleted
		/// </summary>
		public void MarkAsDeleted()
		{
			isDeleted = true;
			isChanged = true;
		}
		
		#endregion
		
		
	}
}
