//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.17929
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace daan.ui.main.LisToShequ88 {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="PEEntity", Namespace="http://www.shequ88.com/")]
    [System.SerializableAttribute()]
    public partial class PEEntity : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string BarCodeField;
        
        private int AgeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LOrganizationField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string STimeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LDoctorField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LtimeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LResultField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string OrderNoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string RemarkField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private daan.ui.main.LisToShequ88.PEReportEntity[] ReportsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ProductNameField;
        
        private int IsSendField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string BarCode {
            get {
                return this.BarCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.BarCodeField, value) != true)) {
                    this.BarCodeField = value;
                    this.RaisePropertyChanged("BarCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=1)]
        public int Age {
            get {
                return this.AgeField;
            }
            set {
                if ((this.AgeField.Equals(value) != true)) {
                    this.AgeField = value;
                    this.RaisePropertyChanged("Age");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string LOrganization {
            get {
                return this.LOrganizationField;
            }
            set {
                if ((object.ReferenceEquals(this.LOrganizationField, value) != true)) {
                    this.LOrganizationField = value;
                    this.RaisePropertyChanged("LOrganization");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string STime {
            get {
                return this.STimeField;
            }
            set {
                if ((object.ReferenceEquals(this.STimeField, value) != true)) {
                    this.STimeField = value;
                    this.RaisePropertyChanged("STime");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string LDoctor {
            get {
                return this.LDoctorField;
            }
            set {
                if ((object.ReferenceEquals(this.LDoctorField, value) != true)) {
                    this.LDoctorField = value;
                    this.RaisePropertyChanged("LDoctor");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string Ltime {
            get {
                return this.LtimeField;
            }
            set {
                if ((object.ReferenceEquals(this.LtimeField, value) != true)) {
                    this.LtimeField = value;
                    this.RaisePropertyChanged("Ltime");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=6)]
        public string LResult {
            get {
                return this.LResultField;
            }
            set {
                if ((object.ReferenceEquals(this.LResultField, value) != true)) {
                    this.LResultField = value;
                    this.RaisePropertyChanged("LResult");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=7)]
        public string OrderNo {
            get {
                return this.OrderNoField;
            }
            set {
                if ((object.ReferenceEquals(this.OrderNoField, value) != true)) {
                    this.OrderNoField = value;
                    this.RaisePropertyChanged("OrderNo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=8)]
        public string Remark {
            get {
                return this.RemarkField;
            }
            set {
                if ((object.ReferenceEquals(this.RemarkField, value) != true)) {
                    this.RemarkField = value;
                    this.RaisePropertyChanged("Remark");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=9)]
        public daan.ui.main.LisToShequ88.PEReportEntity[] Reports {
            get {
                return this.ReportsField;
            }
            set {
                if ((object.ReferenceEquals(this.ReportsField, value) != true)) {
                    this.ReportsField = value;
                    this.RaisePropertyChanged("Reports");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=10)]
        public string ProductName {
            get {
                return this.ProductNameField;
            }
            set {
                if ((object.ReferenceEquals(this.ProductNameField, value) != true)) {
                    this.ProductNameField = value;
                    this.RaisePropertyChanged("ProductName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=11)]
        public int IsSend {
            get {
                return this.IsSendField;
            }
            set {
                if ((this.IsSendField.Equals(value) != true)) {
                    this.IsSendField = value;
                    this.RaisePropertyChanged("IsSend");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="PEReportEntity", Namespace="http://www.shequ88.com/")]
    [System.SerializableAttribute()]
    public partial class PEReportEntity : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ReportIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string StypeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SstateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string InspectorField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ITimeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AuditorField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ATimeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SpecialInfoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string OpinionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ProposalField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string RemarkField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private daan.ui.main.LisToShequ88.FileEntity[] FilesField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private daan.ui.main.LisToShequ88.PEItemEntity[] ItemsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LRoomField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string STimeField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string ReportID {
            get {
                return this.ReportIDField;
            }
            set {
                if ((object.ReferenceEquals(this.ReportIDField, value) != true)) {
                    this.ReportIDField = value;
                    this.RaisePropertyChanged("ReportID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Stype {
            get {
                return this.StypeField;
            }
            set {
                if ((object.ReferenceEquals(this.StypeField, value) != true)) {
                    this.StypeField = value;
                    this.RaisePropertyChanged("Stype");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string Sstate {
            get {
                return this.SstateField;
            }
            set {
                if ((object.ReferenceEquals(this.SstateField, value) != true)) {
                    this.SstateField = value;
                    this.RaisePropertyChanged("Sstate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string Inspector {
            get {
                return this.InspectorField;
            }
            set {
                if ((object.ReferenceEquals(this.InspectorField, value) != true)) {
                    this.InspectorField = value;
                    this.RaisePropertyChanged("Inspector");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string ITime {
            get {
                return this.ITimeField;
            }
            set {
                if ((object.ReferenceEquals(this.ITimeField, value) != true)) {
                    this.ITimeField = value;
                    this.RaisePropertyChanged("ITime");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string Auditor {
            get {
                return this.AuditorField;
            }
            set {
                if ((object.ReferenceEquals(this.AuditorField, value) != true)) {
                    this.AuditorField = value;
                    this.RaisePropertyChanged("Auditor");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=6)]
        public string ATime {
            get {
                return this.ATimeField;
            }
            set {
                if ((object.ReferenceEquals(this.ATimeField, value) != true)) {
                    this.ATimeField = value;
                    this.RaisePropertyChanged("ATime");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=7)]
        public string SpecialInfo {
            get {
                return this.SpecialInfoField;
            }
            set {
                if ((object.ReferenceEquals(this.SpecialInfoField, value) != true)) {
                    this.SpecialInfoField = value;
                    this.RaisePropertyChanged("SpecialInfo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=8)]
        public string Opinion {
            get {
                return this.OpinionField;
            }
            set {
                if ((object.ReferenceEquals(this.OpinionField, value) != true)) {
                    this.OpinionField = value;
                    this.RaisePropertyChanged("Opinion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=9)]
        public string Proposal {
            get {
                return this.ProposalField;
            }
            set {
                if ((object.ReferenceEquals(this.ProposalField, value) != true)) {
                    this.ProposalField = value;
                    this.RaisePropertyChanged("Proposal");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=10)]
        public string Remark {
            get {
                return this.RemarkField;
            }
            set {
                if ((object.ReferenceEquals(this.RemarkField, value) != true)) {
                    this.RemarkField = value;
                    this.RaisePropertyChanged("Remark");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=11)]
        public daan.ui.main.LisToShequ88.FileEntity[] Files {
            get {
                return this.FilesField;
            }
            set {
                if ((object.ReferenceEquals(this.FilesField, value) != true)) {
                    this.FilesField = value;
                    this.RaisePropertyChanged("Files");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=12)]
        public daan.ui.main.LisToShequ88.PEItemEntity[] Items {
            get {
                return this.ItemsField;
            }
            set {
                if ((object.ReferenceEquals(this.ItemsField, value) != true)) {
                    this.ItemsField = value;
                    this.RaisePropertyChanged("Items");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=13)]
        public string LRoom {
            get {
                return this.LRoomField;
            }
            set {
                if ((object.ReferenceEquals(this.LRoomField, value) != true)) {
                    this.LRoomField = value;
                    this.RaisePropertyChanged("LRoom");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=14)]
        public string STime {
            get {
                return this.STimeField;
            }
            set {
                if ((object.ReferenceEquals(this.STimeField, value) != true)) {
                    this.STimeField = value;
                    this.RaisePropertyChanged("STime");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="FileEntity", Namespace="http://www.shequ88.com/")]
    [System.SerializableAttribute()]
    public partial class FileEntity : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ExtensionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private byte[] ContentField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TypeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string RemarkField;
        
        private int FileSizeField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Extension {
            get {
                return this.ExtensionField;
            }
            set {
                if ((object.ReferenceEquals(this.ExtensionField, value) != true)) {
                    this.ExtensionField = value;
                    this.RaisePropertyChanged("Extension");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public byte[] Content {
            get {
                return this.ContentField;
            }
            set {
                if ((object.ReferenceEquals(this.ContentField, value) != true)) {
                    this.ContentField = value;
                    this.RaisePropertyChanged("Content");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string Type {
            get {
                return this.TypeField;
            }
            set {
                if ((object.ReferenceEquals(this.TypeField, value) != true)) {
                    this.TypeField = value;
                    this.RaisePropertyChanged("Type");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string Remark {
            get {
                return this.RemarkField;
            }
            set {
                if ((object.ReferenceEquals(this.RemarkField, value) != true)) {
                    this.RemarkField = value;
                    this.RaisePropertyChanged("Remark");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=4)]
        public int FileSize {
            get {
                return this.FileSizeField;
            }
            set {
                if ((this.FileSizeField.Equals(value) != true)) {
                    this.FileSizeField = value;
                    this.RaisePropertyChanged("FileSize");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="PEItemEntity", Namespace="http://www.shequ88.com/")]
    [System.SerializableAttribute()]
    public partial class PEItemEntity : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ReportIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ICodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MannerField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string RemindField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ValueField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UnitField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string RefValueField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string RemarkField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string ReportID {
            get {
                return this.ReportIDField;
            }
            set {
                if ((object.ReferenceEquals(this.ReportIDField, value) != true)) {
                    this.ReportIDField = value;
                    this.RaisePropertyChanged("ReportID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string ICode {
            get {
                return this.ICodeField;
            }
            set {
                if ((object.ReferenceEquals(this.ICodeField, value) != true)) {
                    this.ICodeField = value;
                    this.RaisePropertyChanged("ICode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string Manner {
            get {
                return this.MannerField;
            }
            set {
                if ((object.ReferenceEquals(this.MannerField, value) != true)) {
                    this.MannerField = value;
                    this.RaisePropertyChanged("Manner");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string Remind {
            get {
                return this.RemindField;
            }
            set {
                if ((object.ReferenceEquals(this.RemindField, value) != true)) {
                    this.RemindField = value;
                    this.RaisePropertyChanged("Remind");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string Value {
            get {
                return this.ValueField;
            }
            set {
                if ((object.ReferenceEquals(this.ValueField, value) != true)) {
                    this.ValueField = value;
                    this.RaisePropertyChanged("Value");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string Unit {
            get {
                return this.UnitField;
            }
            set {
                if ((object.ReferenceEquals(this.UnitField, value) != true)) {
                    this.UnitField = value;
                    this.RaisePropertyChanged("Unit");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=6)]
        public string RefValue {
            get {
                return this.RefValueField;
            }
            set {
                if ((object.ReferenceEquals(this.RefValueField, value) != true)) {
                    this.RefValueField = value;
                    this.RaisePropertyChanged("RefValue");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=7)]
        public string Remark {
            get {
                return this.RemarkField;
            }
            set {
                if ((object.ReferenceEquals(this.RemarkField, value) != true)) {
                    this.RemarkField = value;
                    this.RaisePropertyChanged("Remark");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="InvokeResult", Namespace="http://www.shequ88.com/")]
    [System.SerializableAttribute()]
    public partial class InvokeResult : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private bool SucceedField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MCodeField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public bool Succeed {
            get {
                return this.SucceedField;
            }
            set {
                if ((this.SucceedField.Equals(value) != true)) {
                    this.SucceedField = value;
                    this.RaisePropertyChanged("Succeed");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string MCode {
            get {
                return this.MCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.MCodeField, value) != true)) {
                    this.MCodeField = value;
                    this.RaisePropertyChanged("MCode");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://www.shequ88.com/", ConfigurationName="LisToShequ88.PhysicalExaminationServiceSoap")]
    public interface PhysicalExaminationServiceSoap {
        
        // CODEGEN: 命名空间 http://www.shequ88.com/ 的元素名称 invoker 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://www.shequ88.com/EditPhysicalExamination", ReplyAction="*")]
        daan.ui.main.LisToShequ88.EditPhysicalExaminationResponse EditPhysicalExamination(daan.ui.main.LisToShequ88.EditPhysicalExaminationRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class EditPhysicalExaminationRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="EditPhysicalExamination", Namespace="http://www.shequ88.com/", Order=0)]
        public daan.ui.main.LisToShequ88.EditPhysicalExaminationRequestBody Body;
        
        public EditPhysicalExaminationRequest() {
        }
        
        public EditPhysicalExaminationRequest(daan.ui.main.LisToShequ88.EditPhysicalExaminationRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.shequ88.com/")]
    public partial class EditPhysicalExaminationRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string invoker;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string user;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public daan.ui.main.LisToShequ88.PEEntity data;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string authentic;
        
        public EditPhysicalExaminationRequestBody() {
        }
        
        public EditPhysicalExaminationRequestBody(string invoker, string user, daan.ui.main.LisToShequ88.PEEntity data, string authentic) {
            this.invoker = invoker;
            this.user = user;
            this.data = data;
            this.authentic = authentic;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class EditPhysicalExaminationResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="EditPhysicalExaminationResponse", Namespace="http://www.shequ88.com/", Order=0)]
        public daan.ui.main.LisToShequ88.EditPhysicalExaminationResponseBody Body;
        
        public EditPhysicalExaminationResponse() {
        }
        
        public EditPhysicalExaminationResponse(daan.ui.main.LisToShequ88.EditPhysicalExaminationResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.shequ88.com/")]
    public partial class EditPhysicalExaminationResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public daan.ui.main.LisToShequ88.InvokeResult EditPhysicalExaminationResult;
        
        public EditPhysicalExaminationResponseBody() {
        }
        
        public EditPhysicalExaminationResponseBody(daan.ui.main.LisToShequ88.InvokeResult EditPhysicalExaminationResult) {
            this.EditPhysicalExaminationResult = EditPhysicalExaminationResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface PhysicalExaminationServiceSoapChannel : daan.ui.main.LisToShequ88.PhysicalExaminationServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class PhysicalExaminationServiceSoapClient : System.ServiceModel.ClientBase<daan.ui.main.LisToShequ88.PhysicalExaminationServiceSoap>, daan.ui.main.LisToShequ88.PhysicalExaminationServiceSoap {
        
        public PhysicalExaminationServiceSoapClient() {
        }
        
        public PhysicalExaminationServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public PhysicalExaminationServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public PhysicalExaminationServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public PhysicalExaminationServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        daan.ui.main.LisToShequ88.EditPhysicalExaminationResponse daan.ui.main.LisToShequ88.PhysicalExaminationServiceSoap.EditPhysicalExamination(daan.ui.main.LisToShequ88.EditPhysicalExaminationRequest request) {
            return base.Channel.EditPhysicalExamination(request);
        }
        
        public daan.ui.main.LisToShequ88.InvokeResult EditPhysicalExamination(string invoker, string user, daan.ui.main.LisToShequ88.PEEntity data, string authentic) {
            daan.ui.main.LisToShequ88.EditPhysicalExaminationRequest inValue = new daan.ui.main.LisToShequ88.EditPhysicalExaminationRequest();
            inValue.Body = new daan.ui.main.LisToShequ88.EditPhysicalExaminationRequestBody();
            inValue.Body.invoker = invoker;
            inValue.Body.user = user;
            inValue.Body.data = data;
            inValue.Body.authentic = authentic;
            daan.ui.main.LisToShequ88.EditPhysicalExaminationResponse retVal = ((daan.ui.main.LisToShequ88.PhysicalExaminationServiceSoap)(this)).EditPhysicalExamination(inValue);
            return retVal.Body.EditPhysicalExaminationResult;
        }
    }
}
