/*
insert license info here
*/
using System;

namespace daan.domain
{
	/// <summary>
	///	Generated by MyGeneration using the IBatis Object Mapping template
	/// </summary>
	[Serializable]
	public sealed class Customerresultcomment:BaseDomain
	{
		#region Private Members
		private bool isChanged;
		private bool isDeleted;
		private double? customerresultcommentid; 
		private double? dictcustomerid; 
		private string ordersyear; 
		private string resultcomment; 
		private DateTime? commentdate;
        private DateTime? createdate;
        private string laststartdate;
        private string lastenddate;
        private string thisstartdate;
        private string thisenddate;	
		#endregion
		
		#region Default ( Empty ) Class Constuctor
		/// <summary>
		/// default constructor
		/// </summary>
		public Customerresultcomment()
		{
			customerresultcommentid = null; 
			dictcustomerid = null; 
			ordersyear = null; 
			resultcomment = null; 
			commentdate = new DateTime(); 
			createdate = new DateTime(); 
		}
		#endregion // End of Default ( Empty ) Class Constuctor
		
		#region Public Properties
			
		/// <summary>
		/// 主键
		/// </summary>	
		[LogInfo("主键")]
		public double? Customerresultcommentid
		{
			get { return customerresultcommentid; }
			set { isChanged |= (customerresultcommentid != value); customerresultcommentid = value; }
		}
			
		/// <summary>
		/// 主键，自动ID
		/// </summary>	
		[LogInfo("主键，自动ID")]
		public double? Dictcustomerid
		{
			get { return dictcustomerid; }
			set { isChanged |= (dictcustomerid != value); dictcustomerid = value; }
		}
			
		/// <summary>
		/// 体检年度
		/// </summary>	
		[LogInfo("体检年度")]
		public string Ordersyear
		{
			get { return ordersyear; }
			set	
			{
				if( value!= null && value.Length > 10)
					throw new ArgumentOutOfRangeException("Invalid value for Ordersyear", value, value.ToString());
				
				isChanged |= (ordersyear != value); ordersyear = value;
			}
		}
			
		/// <summary>
		/// 结果建议
		/// </summary>	
		[LogInfo("结果建议")]
		public string Resultcomment
		{
			get { return resultcomment; }
			set	
			{
				resultcomment = value;
			}
		}
			
		/// <summary>
		/// 评价时间
		/// </summary>	
		[LogInfo("评价时间")]
		public DateTime? Commentdate
		{
			get { return commentdate; }
			set { isChanged |= (commentdate != value); commentdate = value; }
		}
			
		/// <summary>
		/// 创建时间
		/// </summary>	
		[LogInfo("创建时间")]
		public DateTime? Createdate
		{
			get { return createdate; }
			set { isChanged |= (createdate != value); createdate = value; }
		}

        /// <summary>
        /// 上次体检开始时间
        /// </summary>
        [LogInfo("上次体检开始时间")]
        public string Laststartdate
        {
            get { return laststartdate; }
            set { laststartdate = value; }
        }

        /// <summary>
        /// 上次体检结束时间
        /// </summary>
        [LogInfo("上次体检结束时间")]
        public string Lastenddate
        {
            get { return lastenddate; }
            set { lastenddate = value; }
        }

        /// <summary>
        /// 这次体检开始时间
        /// </summary>
        [LogInfo("这次体检开始时间")]
        public string Thisstartdate
        {
            get { return thisstartdate; }
            set { thisstartdate = value; }
        }

        /// <summary>
        /// 这体检结束时间
        /// </summary>
        [LogInfo("这体检结束时间")]
        public string Thisenddate
        {
            get { return thisenddate; }
            set { thisenddate = value; }
        }
			
		/// <summary>
		/// Returns whether or not the object has changed it's values.
		/// </summary>
		public bool IsChanged
		{
			get { return isChanged; }
		}
		
		/// <summary>
		/// Returns whether or not the object has changed it's values.
		/// </summary>
		public bool IsDeleted
		{
			get { return isDeleted; }
		}
		
		#endregion 
		
		
		#region Public Functions
		
		/// <summary>
		/// mark the item as deleted
		/// </summary>
		public void MarkAsDeleted()
		{
			isDeleted = true;
			isChanged = true;
		}
		
		#endregion
		
		
	}
}
