//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.296
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace daan.ui.main.SendOrdersToLis {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="SendOrdersToLis.CenterServiceSoap")]
    public interface CenterServiceSoap {
        
        // CODEGEN: 命名空间 http://tempuri.org/ 的元素名称 SiteCode 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Login", ReplyAction="*")]
        daan.ui.main.SendOrdersToLis.LoginResponse Login(daan.ui.main.SendOrdersToLis.LoginRequest request);
        
        // CODEGEN: 命名空间 http://tempuri.org/ 的元素名称 SID 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SendRequestInfo", ReplyAction="*")]
        daan.ui.main.SendOrdersToLis.SendRequestInfoResponse SendRequestInfo(daan.ui.main.SendOrdersToLis.SendRequestInfoRequest request);
        
        // CODEGEN: 命名空间 http://tempuri.org/ 的元素名称 SID 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/QueryResult", ReplyAction="*")]
        daan.ui.main.SendOrdersToLis.QueryResultResponse QueryResult(daan.ui.main.SendOrdersToLis.QueryResultRequest request);
        
        // CODEGEN: 命名空间 http://tempuri.org/ 的元素名称 SID 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SelectPesExceptionLst", ReplyAction="*")]
        daan.ui.main.SendOrdersToLis.SelectPesExceptionLstResponse SelectPesExceptionLst(daan.ui.main.SendOrdersToLis.SelectPesExceptionLstRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class LoginRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Login", Namespace="http://tempuri.org/", Order=0)]
        public daan.ui.main.SendOrdersToLis.LoginRequestBody Body;
        
        public LoginRequest() {
        }
        
        public LoginRequest(daan.ui.main.SendOrdersToLis.LoginRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class LoginRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string SiteCode;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string UserName;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string Password;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string Operator;
        
        public LoginRequestBody() {
        }
        
        public LoginRequestBody(string SiteCode, string UserName, string Password, string Operator) {
            this.SiteCode = SiteCode;
            this.UserName = UserName;
            this.Password = Password;
            this.Operator = Operator;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class LoginResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="LoginResponse", Namespace="http://tempuri.org/", Order=0)]
        public daan.ui.main.SendOrdersToLis.LoginResponseBody Body;
        
        public LoginResponse() {
        }
        
        public LoginResponse(daan.ui.main.SendOrdersToLis.LoginResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class LoginResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string LoginResult;
        
        public LoginResponseBody() {
        }
        
        public LoginResponseBody(string LoginResult) {
            this.LoginResult = LoginResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SendRequestInfoRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SendRequestInfo", Namespace="http://tempuri.org/", Order=0)]
        public daan.ui.main.SendOrdersToLis.SendRequestInfoRequestBody Body;
        
        public SendRequestInfoRequest() {
        }
        
        public SendRequestInfoRequest(daan.ui.main.SendOrdersToLis.SendRequestInfoRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class SendRequestInfoRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string SID;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string SiteCode;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string orders;
        
        public SendRequestInfoRequestBody() {
        }
        
        public SendRequestInfoRequestBody(string SID, string SiteCode, string orders) {
            this.SID = SID;
            this.SiteCode = SiteCode;
            this.orders = orders;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SendRequestInfoResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SendRequestInfoResponse", Namespace="http://tempuri.org/", Order=0)]
        public daan.ui.main.SendOrdersToLis.SendRequestInfoResponseBody Body;
        
        public SendRequestInfoResponse() {
        }
        
        public SendRequestInfoResponse(daan.ui.main.SendOrdersToLis.SendRequestInfoResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class SendRequestInfoResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string SendRequestInfoResult;
        
        public SendRequestInfoResponseBody() {
        }
        
        public SendRequestInfoResponseBody(string SendRequestInfoResult) {
            this.SendRequestInfoResult = SendRequestInfoResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class QueryResultRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="QueryResult", Namespace="http://tempuri.org/", Order=0)]
        public daan.ui.main.SendOrdersToLis.QueryResultRequestBody Body;
        
        public QueryResultRequest() {
        }
        
        public QueryResultRequest(daan.ui.main.SendOrdersToLis.QueryResultRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class QueryResultRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string SID;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string SiteCode;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string RequestCode;
        
        public QueryResultRequestBody() {
        }
        
        public QueryResultRequestBody(string SID, string SiteCode, string RequestCode) {
            this.SID = SID;
            this.SiteCode = SiteCode;
            this.RequestCode = RequestCode;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class QueryResultResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="QueryResultResponse", Namespace="http://tempuri.org/", Order=0)]
        public daan.ui.main.SendOrdersToLis.QueryResultResponseBody Body;
        
        public QueryResultResponse() {
        }
        
        public QueryResultResponse(daan.ui.main.SendOrdersToLis.QueryResultResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class QueryResultResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string QueryResultResult;
        
        public QueryResultResponseBody() {
        }
        
        public QueryResultResponseBody(string QueryResultResult) {
            this.QueryResultResult = QueryResultResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SelectPesExceptionLstRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SelectPesExceptionLst", Namespace="http://tempuri.org/", Order=0)]
        public daan.ui.main.SendOrdersToLis.SelectPesExceptionLstRequestBody Body;
        
        public SelectPesExceptionLstRequest() {
        }
        
        public SelectPesExceptionLstRequest(daan.ui.main.SendOrdersToLis.SelectPesExceptionLstRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class SelectPesExceptionLstRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string SID;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string SiteCode;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string LastDate;
        
        public SelectPesExceptionLstRequestBody() {
        }
        
        public SelectPesExceptionLstRequestBody(string SID, string SiteCode, string LastDate) {
            this.SID = SID;
            this.SiteCode = SiteCode;
            this.LastDate = LastDate;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SelectPesExceptionLstResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SelectPesExceptionLstResponse", Namespace="http://tempuri.org/", Order=0)]
        public daan.ui.main.SendOrdersToLis.SelectPesExceptionLstResponseBody Body;
        
        public SelectPesExceptionLstResponse() {
        }
        
        public SelectPesExceptionLstResponse(daan.ui.main.SendOrdersToLis.SelectPesExceptionLstResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class SelectPesExceptionLstResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string SelectPesExceptionLstResult;
        
        public SelectPesExceptionLstResponseBody() {
        }
        
        public SelectPesExceptionLstResponseBody(string SelectPesExceptionLstResult) {
            this.SelectPesExceptionLstResult = SelectPesExceptionLstResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface CenterServiceSoapChannel : daan.ui.main.SendOrdersToLis.CenterServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class CenterServiceSoapClient : System.ServiceModel.ClientBase<daan.ui.main.SendOrdersToLis.CenterServiceSoap>, daan.ui.main.SendOrdersToLis.CenterServiceSoap {
        
        public CenterServiceSoapClient() {
        }
        
        public CenterServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public CenterServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CenterServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CenterServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        daan.ui.main.SendOrdersToLis.LoginResponse daan.ui.main.SendOrdersToLis.CenterServiceSoap.Login(daan.ui.main.SendOrdersToLis.LoginRequest request) {
            return base.Channel.Login(request);
        }
        
        public string Login(string SiteCode, string UserName, string Password, string Operator) {
            daan.ui.main.SendOrdersToLis.LoginRequest inValue = new daan.ui.main.SendOrdersToLis.LoginRequest();
            inValue.Body = new daan.ui.main.SendOrdersToLis.LoginRequestBody();
            inValue.Body.SiteCode = SiteCode;
            inValue.Body.UserName = UserName;
            inValue.Body.Password = Password;
            inValue.Body.Operator = Operator;
            daan.ui.main.SendOrdersToLis.LoginResponse retVal = ((daan.ui.main.SendOrdersToLis.CenterServiceSoap)(this)).Login(inValue);
            return retVal.Body.LoginResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        daan.ui.main.SendOrdersToLis.SendRequestInfoResponse daan.ui.main.SendOrdersToLis.CenterServiceSoap.SendRequestInfo(daan.ui.main.SendOrdersToLis.SendRequestInfoRequest request) {
            return base.Channel.SendRequestInfo(request);
        }
        
        public string SendRequestInfo(string SID, string SiteCode, string orders) {
            daan.ui.main.SendOrdersToLis.SendRequestInfoRequest inValue = new daan.ui.main.SendOrdersToLis.SendRequestInfoRequest();
            inValue.Body = new daan.ui.main.SendOrdersToLis.SendRequestInfoRequestBody();
            inValue.Body.SID = SID;
            inValue.Body.SiteCode = SiteCode;
            inValue.Body.orders = orders;
            daan.ui.main.SendOrdersToLis.SendRequestInfoResponse retVal = ((daan.ui.main.SendOrdersToLis.CenterServiceSoap)(this)).SendRequestInfo(inValue);
            return retVal.Body.SendRequestInfoResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        daan.ui.main.SendOrdersToLis.QueryResultResponse daan.ui.main.SendOrdersToLis.CenterServiceSoap.QueryResult(daan.ui.main.SendOrdersToLis.QueryResultRequest request) {
            return base.Channel.QueryResult(request);
        }
        
        public string QueryResult(string SID, string SiteCode, string RequestCode) {
            daan.ui.main.SendOrdersToLis.QueryResultRequest inValue = new daan.ui.main.SendOrdersToLis.QueryResultRequest();
            inValue.Body = new daan.ui.main.SendOrdersToLis.QueryResultRequestBody();
            inValue.Body.SID = SID;
            inValue.Body.SiteCode = SiteCode;
            inValue.Body.RequestCode = RequestCode;
            daan.ui.main.SendOrdersToLis.QueryResultResponse retVal = ((daan.ui.main.SendOrdersToLis.CenterServiceSoap)(this)).QueryResult(inValue);
            return retVal.Body.QueryResultResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        daan.ui.main.SendOrdersToLis.SelectPesExceptionLstResponse daan.ui.main.SendOrdersToLis.CenterServiceSoap.SelectPesExceptionLst(daan.ui.main.SendOrdersToLis.SelectPesExceptionLstRequest request) {
            return base.Channel.SelectPesExceptionLst(request);
        }
        
        public string SelectPesExceptionLst(string SID, string SiteCode, string LastDate) {
            daan.ui.main.SendOrdersToLis.SelectPesExceptionLstRequest inValue = new daan.ui.main.SendOrdersToLis.SelectPesExceptionLstRequest();
            inValue.Body = new daan.ui.main.SendOrdersToLis.SelectPesExceptionLstRequestBody();
            inValue.Body.SID = SID;
            inValue.Body.SiteCode = SiteCode;
            inValue.Body.LastDate = LastDate;
            daan.ui.main.SendOrdersToLis.SelectPesExceptionLstResponse retVal = ((daan.ui.main.SendOrdersToLis.CenterServiceSoap)(this)).SelectPesExceptionLst(inValue);
            return retVal.Body.SelectPesExceptionLstResult;
        }
    }
}
